In [2]:
import numpy as np

In [3]:
random_array = np.random.randint(0, 100, size=10)
print(random_array)

[60 60 58  8  1 79 40 79 93 44]


In [4]:
random_array = np.random.randint(0, 50, size=10)
print(random_array)

[33 31 39 17 35 22 41 14 25 35]


In [5]:
avg = np.mean(random_array)
print(random_array)
print(avg)

[33 31 39 17 35 22 41 14 25 35]
29.2


תרגיל 2:

In [8]:
arr1 = np.random.randint(0, 100, size = (3,3))
arr2 = np.random.randint(0, 100, size = (3,3))
result = np.vstack((arr1, arr2))
print(result)
avg = np.mean(result)
print(avg)

[[30 44 62]
 [53 84 64]
 [51 59 92]
 [60  2 13]
 [ 1 56 81]
 [15 29 42]]
46.55555555555556


תרגיל 3:

In [11]:
random_array = np.random.randint(1, 100, size = 20)
print(random_array)
more_than_50 = random_array[random_array > 50]
print(more_than_50)

[77 66 51 43 16 29 29  1 12 82  6 35 86 23 57 56  7 60 16 71]
[77 66 51 82 86 57 56 60 71]


תרגיל 4:

In [13]:
array = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
import random
random.shuffle(array)
print(array)

[8, 7, 9, 1, 5, 4, 6, 2, 3, 10]


In [17]:
import os
print(os.getcwd())
import os

# קבלת שם הקובץ הנוכחי
current_file = os.path.basename(os.getcwd())
print(current_file)



C:\לימודים יד\ADVANCED PYTHON\שיעור 3
שיעור 3
